#!/bin/bash

brew update

brew upgrade

brew install git git-lfs
brew install nvm yarn
#brew install rbenv ruby-build
brew install python
brew install wget --enable-iri
brew install coreutils findutils
brew install openssl
brew install z

#brew install bash zsh

brew install awscli azure-cli 

brew tap azure/functions
brew install azure-functions-core-tools@3

brew install mdcat

brew install terraform

#brew install macvim --override-system-vim

brew install p7zip

brew cask install dotnet-sdk

brew cleanup

